name: Action Test

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag to use'
        type: 'string'
        default: ''
      artifact:
        description: 'Artifact to use'
        type: 'string'
        default: ''

jobs:
  action-setup:
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.os.outputs.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      id: changes
      with:
        filters: |
          action:
          - 'action.yml'
          - '.github/workflows/action-test.yml'
          - '.github/workflows/internal-action-test.yml'
        list-files: shell
    - uses: actions/github-script@v8
      id: os
      env:
        ACTION_CHANGED: ${{ steps.changes.outputs.action }}
      with:
        script: |
          const os = ['ubuntu-latest'];
          // Only run the additional builds if the action has changed, and this
          // is not a test with an artifact image. The additional runs are time
          // consuming so only do them if necessary. Don't run them for artifact
          // action tests because the test won't be multiplatform since the
          // artifact images contain only a single platform.
          if (process.env.ACTION_CHANGED === 'true' && '${{ inputs.artifact }}' === '') {
            os.push('ubuntu-24.04-arm');
            os.push('macos-15-large');
          }
          core.setOutput('os', JSON.stringify(os));

  action-test:
    needs: action-setup
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.action-setup.outputs.os) }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v5
    - uses: ./
      with:
        artifact: ${{ inputs.artifact }}
        tag: ${{ inputs.tag }}
    - name: "Run basic test making sure RPC and Horizon are available"
      run: >
        RESP=`curl --no-progress-meter -X POST -H 'Content-Type: application/json' -d 
        '{"jsonrpc": "2.0", "id": 8675309, "method": "getLatestLedger"}' http://localhost:8000/rpc`
        
        echo "RPC getLatestLedger response: $RESP"

        echo "$RESP" | grep sequence
        
        RESP=`curl -i -o - --silent 'http://localhost:8000/ledgers?limit=1'
        -H 'Accept: application/json'`
        
        echo "Horizon ledgers response: $RESP"
        
        echo "$RESP" | grep "200 OK"
